use num_derive::FromPrimitive;

use crate::commands;
use crate::command;

pub fn mplaysound(comm: WORD,dis:isize) {
    match comm {
        WORD::Sword => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.sword master @s ~ ~ ~",dis),
        WORD::Acacia => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.acacia master @s ~ ~ ~",dis),
        WORD::Arrow => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.arrow master @s ~ ~ ~",dis),
        WORD::Axe => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.axe master @s ~ ~ ~",dis),
        WORD::Bed => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.bed master @s ~ ~ ~",dis),
        WORD::Birch => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.birch master @s ~ ~ ~",dis),
        WORD::Boat => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.boat master @s ~ ~ ~",dis),
        WORD::Book => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.book master @s ~ ~ ~",dis),
        WORD::Boots => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.boots master @s ~ ~ ~",dis),
        WORD::Bow => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.bow master @s ~ ~ ~",dis),
        WORD::Bucket => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.bucket master @s ~ ~ ~",dis),
        WORD::Charcoal => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.charcoal master @s ~ ~ ~",dis),
        WORD::Chest => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.chest master @s ~ ~ ~",dis),
        WORD::Chestplate => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.chestplate master @s ~ ~ ~",dis),
        WORD::Clock => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.clock master @s ~ ~ ~",dis),
        WORD::Coal => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.coal master @s ~ ~ ~",dis),
        WORD::Cobblestone => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.cobblestone master @s ~ ~ ~",dis),
        WORD::Compass => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.compass master @s ~ ~ ~",dis),
        WORD::CopperBlock => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.copper_block master @s ~ ~ ~",dis),
        WORD::CopperIngot => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.copper_ingot master @s ~ ~ ~",dis),
        WORD::CopperOre => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.copper_ore master @s ~ ~ ~",dis),
        WORD::CraftingTable => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.crafting_table master @s ~ ~ ~",dis),
        WORD::DarkOak => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.dark_oak master @s ~ ~ ~",dis),
        WORD::Dirt => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.dirt master @s ~ ~ ~",dis),
        WORD::FishingRod => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.fishing_rod master @s ~ ~ ~",dis),
        WORD::Flint => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.flint master @s ~ ~ ~",dis),
        WORD::FlintAndSteel => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.flint_and_steel master @s ~ ~ ~",dis),
        WORD::Furnace => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.furnace master @s ~ ~ ~",dis),
        WORD::GoldBlock => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.gold_block master @s ~ ~ ~",dis),
        WORD::GoldIngot => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.gold_ingot master @s ~ ~ ~",dis),
        WORD::GoldOre => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.gold_ore master @s ~ ~ ~",dis),
        WORD::Helmet => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.helmet master @s ~ ~ ~",dis),
        WORD::Hoe => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.hoe master @s ~ ~ ~",dis),
        WORD::HorseArmor => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.horse_armor master @s ~ ~ ~",dis),
        WORD::IronBlock => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.iron_block master @s ~ ~ ~",dis),
        WORD::IronIngot => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.iron_ingot master @s ~ ~ ~",dis),
        WORD::IronOre => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.iron_ore master @s ~ ~ ~",dis),
        WORD::JungleTree => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.jungle_tree master @s ~ ~ ~",dis),
        WORD::Ladder => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.ladder master @s ~ ~ ~",dis),
        WORD::Lead => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.lead master @s ~ ~ ~",dis),
        WORD::Leggings => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.leggings master @s ~ ~ ~",dis),
        WORD::Mangrove => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.mangrove master @s ~ ~ ~",dis),
        WORD::Map => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.map master @s ~ ~ ~"),
        WORD::MusicDisc => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.music_disc master @s ~ ~ ~",dis),
        WORD::NameTag => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.name_tag master @s ~ ~ ~",dis),
        WORD::Paper => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.paper master @s ~ ~ ~",dis),
        WORD::Pickaxe => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.pickaxe master @s ~ ~ ~",dis),
        WORD::Plank => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.plank master @s ~ ~ ~",dis),
        WORD::RawCopper => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.raw_copper master @s ~ ~ ~",dis),
        WORD::RawGold => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.raw_gold master @s ~ ~ ~",dis),
        WORD::RawIron => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.raw_iron master @s ~ ~ ~",dis),
        WORD::Saddle => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.saddle master @s ~ ~ ~",dis),
        WORD::Sand => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.sand master @s ~ ~ ~",dis),
        WORD::Shears => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.shears master @s ~ ~ ~",dis),
        WORD::Shield => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.shield master @s ~ ~ ~",dis),
        WORD::Shovel => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.shovel master @s ~ ~ ~",dis),
        WORD::Spruce => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.spruce master @s ~ ~ ~",dis),
        WORD::Spyglass => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.spyglass master @s ~ ~ ~",dis),
        WORD::Stick => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.stick master @s ~ ~ ~",dis),
        WORD::Stone => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.stone master @s ~ ~ ~",dis),
        WORD::TotemOfUndying => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.totem_of_undying master @s ~ ~ ~",dis),
        WORD::Wood => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.wood master @s ~ ~ ~",dis),
        WORD::Zombie => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.zombie master @s ~ ~ ~",dis),
        WORD::Creeper => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.creeper master @s ~ ~ ~",dis),
        WORD::Spider => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.spider master @s ~ ~ ~",dis),
        WORD::CaveSpider => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.cave_spider master @s ~ ~ ~",dis),
        WORD::Witch => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.witch master @s ~ ~ ~",dis),
        WORD::Enderman => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.enderman master @s ~ ~ ~",dis),
        WORD::Slime => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.slime master @s ~ ~ ~",dis),
        WORD::ZombieVillager => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.zombie_villager master @s ~ ~ ~",dis),
        WORD::Drowned => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.drowned master @s ~ ~ ~",dis),
        WORD::Guardian => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.guardian master @s ~ ~ ~",dis),
        WORD::Husk => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.husk master @s ~ ~ ~",dis),
        WORD::Stray => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.stray master @s ~ ~ ~",dis),
        WORD::ChickenJockey => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.chicken_jockey master @s ~ ~ ~",dis),
        WORD::SpiderJockey => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.spider_jockey master @s ~ ~ ~",dis),
        WORD::SkeltonHorseman => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.skelton_horseman master @s ~ ~ ~",dis),
        WORD::Sheep => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.sheep master @s ~ ~ ~",dis),
        WORD::Cow => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.cow master @s ~ ~ ~",dis),
        WORD::Pig => command!("execute as @a[distance=0..{}] at @s run playsound tango.pig master @s ~ ~ ~",dis),
        WORD::Chicken => command!("execute as @a[distance=0..{}] at @s run playsound tango.chicken master @s ~ ~ ~",dis),
        WORD::Horse => command!("execute as @a[distance=0..{}] at @s run playsound tango.horse master @s ~ ~ ~",dis),
        WORD::Llama => command!("execute as @a[distance=0..{}] at @s run playsound tango.llama master @s ~ ~ ~",dis),
        WORD::Donkey => command!("execute as @a[distance=0..{}] at @s run playsound tango.donkey master @s ~ ~ ~",dis),
        WORD::Camel => command!("execute as @a[distance=0..{}] at @s run playsound tango.camel master @s ~ ~ ~",dis),
        WORD::Cat => command!("execute as @a[distance=0..{}] at @s run playsound tango.cat master @s ~ ~ ~",dis),
        WORD::Wolf => command!("execute as @a[distance=0..{}] at @s run playsound tango.wolf master @s ~ ~ ~",dis),
        WORD::Fox => command!("execute as @a[distance=0..{}] at @s run playsound tango.fox master @s ~ ~ ~",dis),
        WORD::Rabbit => command!("execute as @a[distance=0..{}] at @s run playsound tango.rabbit master @s ~ ~ ~",dis),
        WORD::Parrot => command!("execute as @a[distance=0..{}] at @s run playsound tango.parrot master @s ~ ~ ~",dis),
        WORD::Panda => command!("execute as @a[distance=0..{}] at @s run playsound tango.panda master @s ~ ~ ~",dis),
        WORD::Ocelot => command!("execute as @a[distance=0..{}] at @s run playsound tango.ocelot master @s ~ ~ ~",dis),
        WORD::Bee => command!("execute as @a[distance=0..{}] at @s run playsound tango.bee master @s ~ ~ ~",dis),
        WORD::Turtle => command!("execute as @a[distance=0..{}] at @s run playsound tango.turtle master @s ~ ~ ~",dis),
        WORD::Dolphin => command!("execute as @a[distance=0..{}] at @s run playsound tango.dolphin master @s ~ ~ ~",dis),
        WORD::Axolotl => command!("execute as @a[distance=0..{}] at @s run playsound tango.axolotl master @s ~ ~ ~",dis),
        WORD::Tropicalfish => command!("execute as @a[distance=0..{}] at @s run playsound tango.tropical_fish master @s ~ ~ ~",dis),
        WORD::Cod => command!("execute as @a[distance=0..{}] at @s run playsound tango.cod master @s ~ ~ ~",dis),
        WORD::Salmon => command!("execute as @a[distance=0..{}] at @s run playsound tango.salmon master @s ~ ~ ~",dis),
        WORD::Pufferfish => command!("execute as @a[distance=0..{}] at @s run playsound tango.pufferfish master @s ~ ~ ~",dis),
        WORD::Squid => command!("execute as @a[distance=0..{}] at @s run playsound tango.squid master @s ~ ~ ~",dis),
        WORD::GlowSquid => command!("execute as @a[distance=0..{}] at @s run playsound tango.glow_squid master @s ~ ~ ~",dis),
        WORD::One => command!("execute as @a[distance=0..{}] at @s run playsound tango.one master @s ~ ~ ~",dis),
        WORD::Two => command!("execute as @a[distance=0..{}] at @s run playsound tango.two master @s ~ ~ ~",dis),
        WORD::Three => command!("execute as @a[distance=0..{}] at @s run playsound tango.three master @s ~ ~ ~",dis),
        WORD::Four => command!("execute as @a[distance=0..{}] at @s run playsound tango.four master @s ~ ~ ~",dis),
        WORD::Five => command!("execute as @a[distance=0..{}] at @s run playsound tango.five master @s ~ ~ ~",dis),
        WORD::Six => command!("execute as @a[distance=0..{}] at @s run playsound tango.six master @s ~ ~ ~",dis),
        WORD::Seven => command!("execute as @a[distance=0..{}] at @s run playsound tango.seven master @s ~ ~ ~",dis),
        WORD::Eight => command!("execute as @a[distance=0..{}] at @s run playsound tango.eight master @s ~ ~ ~",dis),
        WORD::Nin => command!("execute as @a[distance=0..{}] at @s run playsound tango.nin master @s ~ ~ ~",dis),
        WORD::Eleven => command!("execute as @a[distance=0..{}] at @s run playsound tango.eleven master @s ~ ~ ~",dis),
        WORD::Twelve => command!("execute as @a[distance=0..{}] at @s run playsound tango.twelve master @s ~ ~ ~",dis),
        WORD::Thirteen => command!("execute as @a[distance=0..{}] at @s run playsound tango.thirteen master @s ~ ~ ~",dis),
        WORD::Fourteen => command!("execute as @a[distance=0..{}] at @s run playsound tango.fourteen master @s ~ ~ ~",dis),
        WORD::Fifteen => command!("execute as @a[distance=0..{}] at @s run playsound tango.fifteen master @s ~ ~ ~",dis),
        WORD::Sixteen => command!("execute as @a[distance=0..{}] at @s run playsound tango.sixteen master @s ~ ~ ~",dis),
        WORD::Seventeen => command!("execute as @a[distance=0..{}] at @s run playsound tango.seventeen master @s ~ ~ ~",dis),
        WORD::Eighteen => command!("execute as @a[distance=0..{}] at @s run playsound tango.eighteen master @s ~ ~ ~",dis),
        WORD::Nineteen => command!("execute as @a[distance=0..{}] at @s run playsound tango.nineteen master @s ~ ~ ~",dis),
        WORD::Twenty => command!("execute as @a[distance=0..{}] at @s run playsound tango.twenty master @s ~ ~ ~",dis),
        WORD::Red => command!("execute as @a[distance=0..{}] at @s run playsound tango.red master @s ~ ~ ~",dis),
        WORD::Blue => command!("execute as @a[distance=0..{}] at @s run playsound tango.blue master @s ~ ~ ~",dis),
        WORD::Yellow => command!("execute as @a[distance=0..{}] at @s run playsound tango.yellow master @s ~ ~ ~",dis),
        WORD::Green => command!("execute as @a[distance=0..{}] at @s run playsound tango.green master @s ~ ~ ~",dis),
        WORD::Orange => command!("execute as @a[distance=0..{}] at @s run playsound tango.orange master @s ~ ~ ~",dis),
        WORD::White => command!("execute as @a[distance=0..{}] at @s run playsound tango.white master @s ~ ~ ~",dis),
        WORD::Black => command!("execute as @a[distance=0..{}] at @s run playsound tango.black master @s ~ ~ ~",dis),
        WORD::Gray => command!("execute as @a[distance=0..{}] at @s run playsound tango.gray master @s ~ ~ ~",dis),
        WORD::Brown => command!("execute as @a[distance=0..{}] at @s run playsound tango.brown master @s ~ ~ ~",dis),
        WORD::Purple => command!("execute as @a[distance=0..{}] at @s run playsound tango.purple master @s ~ ~ ~",dis),
        WORD::Pink => command!("execute as @a[distance=0..{}] at @s run playsound tango.pink master @s ~ ~ ~",dis),
        WORD::Lime => command!("execute as @a[distance=0..{}] at @s run playsound tango.lime master @s ~ ~ ~",dis),
        WORD::Cyane => command!("execute as @a[distance=0..{}] at @s run playsound tango.cyane master @s ~ ~ ~",dis),
        WORD::LightBlue => command!("execute as @a[distance=0..{}] at @s run playsound tango.light_blue master @s ~ ~ ~",dis),
        WORD::LightGray => command!("execute as @a[distance=0..{}] at @s run playsound tango.light_gray master @s ~ ~ ~",dis),
        WORD::Magenta => command!("execute as @a[distance=0..{}] at @s run playsound tango.magenta master @s ~ ~ ~",dis),

        _ => {}
    }
}

#[derive(FromPrimitive, Clone, Copy, Debug)]
#[repr(usize)]
pub enum WORD {
    Sword = 0,
    Axe,
    Pickaxe,
    Shovel,
    Bow,
    Arrow,
    FishingRod,
    Hoe,
    Bucket,
    Shears,
    Saddle,
    Lead,
    Boat,
    Paper,
    Book,
    Map,
    Compass,
    Clock,
    CraftingTable,
    Furnace,
    Chest,
    Bed,
    Coal,
    Charcoal,
    Flint,
    FlintAndSteel,
    Ladder,
    NameTag,
    Spyglass,
    MusicDisc,
    Helmet,
    Chestplate,
    Leggings,
    Boots,
    Shield,
    TotemOfUndying,
    HorseArmor,
    IronOre,
    RawIron,
    IronIngot,
    IronBlock,
    GoldOre,
    RawGold,
    GoldIngot,
    GoldBlock,
    CopperOre,
    RawCopper,
    CopperIngot,
    CopperBlock,
    Stone,
    Cobblestone,
    Sand,
    Dirt,
    Tree,
    Wood,
    Plank,
    Stick,
    Oak,
    Spruce,
    Birch,
    JungleTree,
    Acacia,
    DarkOak,
    Mangrove = 63,
    Zombie = 64,
    Creeper,
    Skelton,
    Spider,
    CaveSpider,
    Witch,
    Enderman,
    Slime,
    ZombieVillager,
    Drowned,
    Guardian,
    ElderGuardian,
    Husk,
    Stray,
    ChickenJockey,
    SpiderJockey,
    SkeltonHorseman,
    Sheep,
    Cow,
    Pig,
    Chicken,
    Horse,
    Llama,
    Donkey,
    Camel,
    Cat,
    Wolf,
    Fox,
    Rabbit,
    Parrot,
    Panda,
    Ocelot,
    Bee,
    Turtle,
    Dolphin,
    Axolotl,
    Tropicalfish,
    Cod,
    Salmon,
    Pufferfish,
    Squid,
    GlowSquid = 106,
    One = 107,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nin,
    Ten,
    Eleven,
    Twelve,
    Thirteen,
    Fourteen,
    Fifteen,
    Sixteen,
    Seventeen,
    Eighteen,
    Nineteen,
    Twenty,
    Red,
    Blue,
    Yellow,
    Green,
    Orange,
    White,
    Black,
    Gray,
    Brown,
    Purple,
    Pink,
    Lime,
    Cyane,
    LightBlue,
    LightGray,
    Magenta = 142,
    None,
}
