use num_derive::FromPrimitive;

use crate::commands;
use crate::command;

pub fn mplaysound(comm: WORD,dis:isize) {
    match comm {
        WORD::Sword => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.sword master @s ~ ~ ~",dis),
        WORD::Acacia => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.acacia master @s ~ ~ ~",dis),
        WORD::Arrow => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.arrow master @s ~ ~ ~",dis),
        WORD::Axe => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.axe master @s ~ ~ ~",dis),
        WORD::Bed => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.bed master @s ~ ~ ~",dis),
        WORD::Birch => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.birch master @s ~ ~ ~",dis),
        WORD::Boat => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.boat master @s ~ ~ ~",dis),
        WORD::Book => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.book master @s ~ ~ ~",dis),
        WORD::Boots => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.boots master @s ~ ~ ~",dis),
        WORD::Bow => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.bow master @s ~ ~ ~",dis),
        WORD::Bucket => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.bucket master @s ~ ~ ~",dis),
        WORD::Charcoal => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.charcoal master @s ~ ~ ~",dis),
        WORD::Chest => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.chest master @s ~ ~ ~",dis),
        WORD::Chestplate => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.chestplate master @s ~ ~ ~",dis),
        WORD::Clock => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.clock master @s ~ ~ ~",dis),
        WORD::Coal => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.coal master @s ~ ~ ~",dis),
        WORD::Cobblestone => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.cobblestone master @s ~ ~ ~",dis),
        WORD::Compass => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.compass master @s ~ ~ ~",dis),
        WORD::CopperBlock => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.copper_block master @s ~ ~ ~",dis),
        WORD::CopperIngot => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.copper_ingot master @s ~ ~ ~",dis),
        WORD::CopperOre => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.copper_ore master @s ~ ~ ~",dis),
        WORD::CraftingTable => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.crafting_table master @s ~ ~ ~",dis),
        WORD::DarkOak => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.dark_oak master @s ~ ~ ~",dis),
        WORD::Dirt => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.dirt master @s ~ ~ ~",dis),
        WORD::FishingRod => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.fishing_rod master @s ~ ~ ~",dis),
        WORD::Flint => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.flint master @s ~ ~ ~",dis),
        WORD::FlintAndSteel => {
            command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.flint_and_steel master @s ~ ~ ~",dis)
        }
        WORD::Furnace => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.furnace master @s ~ ~ ~",dis),
        WORD::GoldBlock => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.gold_block master @s ~ ~ ~",dis),
        WORD::GoldIngot => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.gold_ingot master @s ~ ~ ~",dis),
        WORD::GoldOre => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.gold_ore master @s ~ ~ ~",dis),
        WORD::Helmet => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.helmet master @s ~ ~ ~",dis),
        WORD::Hoe => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.hoe master @s ~ ~ ~",dis),
        WORD::HorseArmor => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.horse_armor master @s ~ ~ ~",dis),
        WORD::IronBlock => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.iron_block master @s ~ ~ ~",dis),
        WORD::IronIngot => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.iron_ingot master @s ~ ~ ~",dis),
        WORD::IronOre => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.iron_ore master @s ~ ~ ~",dis),
        WORD::JungleTree => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.jungle_tree master @s ~ ~ ~",dis),
        WORD::Ladder => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.ladder master @s ~ ~ ~",dis),
        WORD::Lead => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.lead master @s ~ ~ ~",dis),
        WORD::Leggings => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.leggings master @s ~ ~ ~",dis),
        WORD::Mangrove => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.mangrove master @s ~ ~ ~",dis),
        WORD::Map => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.map master @s ~ ~ ~"),
        WORD::MusicDisc => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.music_disc master @s ~ ~ ~",dis),
        WORD::NameTag => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.name_tag master @s ~ ~ ~",dis),
        WORD::Paper => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.paper master @s ~ ~ ~",dis),
        WORD::Pickaxe => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.pickaxe master @s ~ ~ ~",dis),
        WORD::Plank => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.plank master @s ~ ~ ~",dis),
        WORD::RawCopper => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.raw_copper master @s ~ ~ ~",dis),
        WORD::RawGold => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.raw_gold master @s ~ ~ ~",dis),
        WORD::RawIron => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.raw_iron master @s ~ ~ ~",dis),
        WORD::Saddle => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.saddle master @s ~ ~ ~",dis),
        WORD::Sand => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.sand master @s ~ ~ ~",dis),
        WORD::Shears => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.shears master @s ~ ~ ~",dis),
        WORD::Shield => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.shield master @s ~ ~ ~",dis),
        WORD::Shovel => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.shovel master @s ~ ~ ~",dis),
        WORD::Spruce => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.spruce master @s ~ ~ ~",dis),
        WORD::Spyglass => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.spyglass master @s ~ ~ ~",dis),
        WORD::Stick => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.stick master @s ~ ~ ~",dis),
        WORD::Stone => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.stone master @s ~ ~ ~",dis),
        WORD::TotemOfUndying => {
            command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.totem_of_undying master @s ~ ~ ~",dis)
        }
        WORD::Wood => command!("execute as @a[distance=0..{}] at @s run playsound minecraft:tango.wood master @s ~ ~ ~",dis),
        _ => {}
    }
}

#[derive(FromPrimitive, Clone, Copy, Debug)]
#[repr(usize)]
pub enum WORD {
    Sword = 0,
    Axe,
    Pickaxe,
    Shovel,
    Bow,
    Arrow,
    FishingRod,
    Hoe,
    Bucket,
    Shears,
    Saddle,
    Lead,
    Boat,
    Paper,
    Book,
    Map,
    Compass,
    Clock,
    CraftingTable,
    Furnace,
    Chest,
    Bed,
    Coal,
    Charcoal,
    Flint,
    FlintAndSteel,
    Ladder,
    NameTag,
    Spyglass,
    MusicDisc,
    Helmet,
    Chestplate,
    Leggings,
    Boots,
    Shield,
    TotemOfUndying,
    HorseArmor,
    IronOre,
    RawIron,
    IronIngot,
    IronBlock,
    GoldOre,
    RawGold,
    GoldIngot,
    GoldBlock,
    CopperOre,
    RawCopper,
    CopperIngot,
    CopperBlock,
    Stone,
    Cobblestone,
    Sand,
    Dirt,
    Tree,
    Wood,
    Plank,
    Stick,
    Oak,
    Spruce,
    Birch,
    JungleTree,
    Acacia,
    DarkOak,
    Mangrove = 63,
    Zombie = 64,
    Creeper,
    Skelton,
    Spider,
    CaveSpider,
    Witch,
    Enderman,
    Slime,
    ZombieVillager,
    Drowned,
    Guardian,
    ElderGuardian,
    Husk,
    Stray,
    ChickenJockey,
    SpiderJockey,
    SkeltonHorseman,
    Sheep,
    Cow,
    Pig,
    Chicken,
    Horse,
    Llama,
    Donkey,
    Camel,
    Cat,
    Wolf,
    Fox,
    Rabbit,
    Parrot,
    Panda,
    Ocelot,
    Bee,
    Turtle,
    Dolphin,
    Axolotl,
    Tropical,
    Fish,
    Cod,
    Salmon,
    Pufferfish,
    Squid,
    GlowSquid = 106,
    None,
}
